version: '3.8'
services:
  web:
    build:
      context: .
      args:
        - VERSION=${VERSION:-v1}
    ports:
      - "8080:5000"
    environment:
      - APP_VERSION=${VERSION:-v1}
    restart: unless-stopped