version: '3.8'
services:
  web:
    build:
      context: ./${VERSION:-v1}
      dockerfile: ../Dockerfile
      args:
        - APP_VERSION=${VERSION:-v1}
    ports:
      - "5000:5000"
    environment:
      - APP_VERSION=${VERSION:-v1}
    restart: unless-stopped