version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_VERSION=${VERSION:-$(cat VERSION)}
    ports:
      - "5000:5000"
    environment:
      - APP_VERSION=${VERSION:-$(cat VERSION)}
    restart: unless-stopped