# .github/workflows/deploy.yml
name: Build and Push to DockerHub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set VERSION environment variable
      run: |
        echo "VERSION=$(cat VERSION | tr -d '\n\r\t ')" >> $GITHUB_ENV
        echo "Building version: $(cat VERSION)"
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        build-args: |
          APP_VERSION=${{ env.VERSION }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/rng-flask-app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/rng-flask-app:${{ env.VERSION }}